// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeCXP-fQ5chNLdaWdlKr0cPdrTwgN86U',
    appId: '1:867334529574:web:a241d36654227226913ce7',
    messagingSenderId: '867334529574',
    projectId: 'nutricarewellness-live',
    authDomain: 'nutricarewellness-live.firebaseapp.com',
    storageBucket: 'nutricarewellness-live.firebasestorage.app',
    measurementId: 'G-8MNGDBHXJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2H_8_J8Ba1hmJ2SZIMvFo1oxeql1RRo',
    appId: '1:867334529574:android:9b0a800b555af4fa913ce7',
    messagingSenderId: '867334529574',
    projectId: 'nutricarewellness-live',
    storageBucket: 'nutricarewellness-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsFWQoz1-OoLkTqxZqOujNsjbnv_2sbm0',
    appId: '1:867334529574:ios:240ffbf991e715a7913ce7',
    messagingSenderId: '867334529574',
    projectId: 'nutricarewellness-live',
    storageBucket: 'nutricarewellness-live.firebasestorage.app',
    iosBundleId: 'com.nutricarewellness.nutricareConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsFWQoz1-OoLkTqxZqOujNsjbnv_2sbm0',
    appId: '1:867334529574:ios:240ffbf991e715a7913ce7',
    messagingSenderId: '867334529574',
    projectId: 'nutricarewellness-live',
    storageBucket: 'nutricarewellness-live.firebasestorage.app',
    iosBundleId: 'com.nutricarewellness.nutricareConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACeCXP-fQ5chNLdaWdlKr0cPdrTwgN86U',
    appId: '1:867334529574:web:289a5d5aad18d357913ce7',
    messagingSenderId: '867334529574',
    projectId: 'nutricarewellness-live',
    authDomain: 'nutricarewellness-live.firebaseapp.com',
    storageBucket: 'nutricarewellness-live.firebasestorage.app',
    measurementId: 'G-FSH2K5CQQH',
  );
}
