// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_guest.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsGuest {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYWMATJ_mUSaKGrQg_8c4zHKmkyLvWQng',
    appId: '1:349866160528:web:8ef09ee6385deb0ef8c315',
    messagingSenderId: '349866160528',
    projectId: 'nutricarewellness-guest',
    authDomain: 'nutricarewellness-guest.firebaseapp.com',
    storageBucket: 'nutricarewellness-guest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmHTmDXIea41FDBBbhsA8hiGsmrkMgNAE',
    appId: '1:349866160528:android:09818a86eb933f6ef8c315',
    messagingSenderId: '349866160528',
    projectId: 'nutricarewellness-guest',
    storageBucket: 'nutricarewellness-guest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3EG2EnEee-75Ios--b5M43N-QqPkx-k',
    appId: '1:349866160528:ios:24294c54a9ca945bf8c315',
    messagingSenderId: '349866160528',
    projectId: 'nutricarewellness-guest',
    storageBucket: 'nutricarewellness-guest.firebasestorage.app',
    iosBundleId: 'com.nutricarewellness.nutricareConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe3EG2EnEee-75Ios--b5M43N-QqPkx-k',
    appId: '1:349866160528:ios:24294c54a9ca945bf8c315',
    messagingSenderId: '349866160528',
    projectId: 'nutricarewellness-guest',
    storageBucket: 'nutricarewellness-guest.firebasestorage.app',
    iosBundleId: 'com.nutricarewellness.nutricareConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYWMATJ_mUSaKGrQg_8c4zHKmkyLvWQng',
    appId: '1:349866160528:web:9e42a148ddecb9abf8c315',
    messagingSenderId: '349866160528',
    projectId: 'nutricarewellness-guest',
    authDomain: 'nutricarewellness-guest.firebaseapp.com',
    storageBucket: 'nutricarewellness-guest.firebasestorage.app',
  );
}
