// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEEDCD0Y9UKs35CurDb2YSy2WuQgptb8c',
    appId: '1:119840373203:web:34aeb7af1aa70a79985726',
    messagingSenderId: '119840373203',
    projectId: 'nwgoaltracker',
    authDomain: 'nwgoaltracker.firebaseapp.com',
    databaseURL: 'https://nwgoaltracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nwgoaltracker.firebasestorage.app',
    measurementId: 'G-61708N94S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCELEvqFdN6v-z4lD2UyY7dGJDa3X49tZo',
    appId: '1:119840373203:android:2428ceee929e3609985726',
    messagingSenderId: '119840373203',
    projectId: 'nwgoaltracker',
    databaseURL: 'https://nwgoaltracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nwgoaltracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC272-pIUytv1K3gaMXzYzw0wdW_ZDTFSE',
    appId: '1:119840373203:ios:401e2fa2edfb4139985726',
    messagingSenderId: '119840373203',
    projectId: 'nwgoaltracker',
    databaseURL: 'https://nwgoaltracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nwgoaltracker.firebasestorage.app',
    iosBundleId: 'com.nutricarewellness.nutricareConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC272-pIUytv1K3gaMXzYzw0wdW_ZDTFSE',
    appId: '1:119840373203:ios:401e2fa2edfb4139985726',
    messagingSenderId: '119840373203',
    projectId: 'nwgoaltracker',
    databaseURL: 'https://nwgoaltracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nwgoaltracker.firebasestorage.app',
    iosBundleId: 'com.nutricarewellness.nutricareConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEEDCD0Y9UKs35CurDb2YSy2WuQgptb8c',
    appId: '1:119840373203:web:34142166aff77042985726',
    messagingSenderId: '119840373203',
    projectId: 'nwgoaltracker',
    authDomain: 'nwgoaltracker.firebaseapp.com',
    databaseURL: 'https://nwgoaltracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nwgoaltracker.firebasestorage.app',
    measurementId: 'G-0QS24BX09J',
  );

}