import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:logger/logger.dart';
import 'package:nutricare_connect/features/dietplan/PRESENTATION/screens/client_dashboard_main_screen.dart' hide MeetingModel;
import 'package:nutricare_connect/features/dietplan/domain/entities/schedule_meeting_utils.dart';

// --- Logger Setup ---
final Logger _logger = Logger(
  printer: PrettyPrinter(
    methodCount: 0,
    errorMethodCount: 5,
    lineLength: 80,
    colors: true,
    printEmojis: true,
    printTime: false,
  ),
);

class MeetingService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  // Use a dedicated collection for meetings
  final String _collectionName = 'client_meetings';

  CollectionReference<Map<String, dynamic>> get _meetingsCollection =>
      _firestore.collection(_collectionName);

  /// Fetches all meeting records for a specific client ID, sorted by start time.
  Future<List<MeetingModel>> getClientMeetings(String clientId) async {
    try {
      _logger.d('Fetching meetings for client: $clientId');

      final querySnapshot = await _meetingsCollection
          .where('clientId', isEqualTo: clientId)
      // Sort by start time for consistent display (most recent first)
          .orderBy('startTime', descending: true)
          .get();

      final meetings = querySnapshot.docs.map((doc) {
        return MeetingModel.fromFirestore(doc);
      }).toList();

      _logger.i('Successfully fetched ${meetings.length} meetings.');
      return meetings;

    } on FirebaseException catch (e) {
      _logger.e('Firebase Error fetching meetings: ${e.code} - ${e.message}');
      throw Exception('Failed to load meetings: ${e.message}');
    } catch (e) {
      _logger.e('Unknown Error fetching meetings: ${e.toString()}');
      throw Exception('An unexpected error occurred while loading meetings.');
    }
  }

  /// Schedules a new meeting by adding a document to Firestore.
  Future<void> scheduleMeeting({
    required String clientId,
    required DateTime startTime,
    required String meetingType,
    required String purpose,
    String? meetLink,
    String? clinicalNotes
  }) async {
    try {
      _logger.d('Attempting to schedule new meeting for client: $clientId at $startTime');

      final newMeeting = MeetingModel(
        id: '', // ID will be generated by Firestore
        clientId: clientId,
        startTime: startTime,
        meetingType: meetingType,
        purpose: purpose,
        status: MeetingStatus.scheduled,
        meetLink: meetLink,
        clinicalNotes: clinicalNotes, createdAt: Timestamp.now() , updatedAt: Timestamp.now(),
      );

      // Add a new document to the collection
      await _meetingsCollection.add(newMeeting.toFirestore(isNew: true));
      _logger.i('New meeting scheduled successfully.');

    } on FirebaseException catch (e) {
      _logger.e('Firebase Error scheduling meeting: ${e.code} - ${e.message}');
      throw Exception('Failed to schedule meeting: ${e.message}');
    } catch (e) {
      _logger.e('Unknown Error scheduling meeting: ${e.toString()}');
      throw Exception('An unexpected error occurred while scheduling the meeting.');
    }
  }

  /// Updates the status and/or clinical notes of an existing meeting.
  Future<void> updateMeeting(MeetingModel meeting) async {
    try {
      _logger.d('Attempting to update meeting ID: ${meeting.id}');

      // Update the specific document by its ID
      await _meetingsCollection.doc(meeting.id).update({
        'status': meeting.status.name,
        'clinicalNotes': meeting.clinicalNotes,
        'updatedAt': FieldValue.serverTimestamp(),
      });

      _logger.i('Meeting ${meeting.id} updated successfully.');

    } on FirebaseException catch (e) {
      if (e.code == 'not-found') {
        throw Exception('Meeting not found. ID: ${meeting.id}');
      }
      _logger.e('Firebase Error updating meeting: ${e.code} - ${e.message}');
      throw Exception('Failed to update meeting: ${e.message}');
    } catch (e) {
      _logger.e('Unknown Error updating meeting: ${e.toString()}');
      throw Exception('An unexpected error occurred while updating the meeting.');
    }
  }

  /// Fetches all meeting records across all clients, sorted by start time.
  Future<List<MeetingModel>> getAllMeetings() async {
    try {
      // 🎯 No 'where' clause, fetches all documents in the collection
      final querySnapshot = await _meetingsCollection
          .orderBy('startTime', descending: true)
          .get();

      final meetings = querySnapshot.docs.map((doc) {
        return MeetingModel.fromFirestore(doc);
      }).toList();

      _logger.i('Successfully fetched ${meetings.length} total meetings.');
      return meetings;

    } on FirebaseException catch (e) {
      _logger.e('Firebase Error fetching all meetings: ${e.code} - ${e.message}');
      throw Exception('Failed to load all meetings: ${e.message}');
    } catch (e) {
      _logger.e('Unknown Error fetching all meetings: ${e.toString()}');
      throw Exception('An unexpected error occurred while loading meetings.');
    }
  }

  /// Updates the start time and status (to scheduled) of an existing meeting.
  Future<void> rescheduleMeeting({
    required String meetingId,
    required DateTime newStartTime,
    required String notes, // Mandatory note
  }) async {
    try {
      _logger.d('Attempting to reschedule meeting ID: $meetingId to $newStartTime');

      await _meetingsCollection.doc(meetingId).update({
        'startTime': Timestamp.fromDate(newStartTime),
        'status': MeetingStatus.scheduled.name, // Force back to scheduled
        'clinicalNotes': notes, // Mandatory note
        'updatedAt': FieldValue.serverTimestamp(),
      });

      _logger.i('Meeting $meetingId rescheduled successfully.');

    } on FirebaseException catch (e) {
      if (e.code == 'not-found') {
        throw Exception('Meeting not found. ID: $meetingId');
      }
      _logger.e('Firebase Error rescheduling meeting: ${e.code} - ${e.message}');
      throw Exception('Failed to reschedule meeting: ${e.message}');
    } catch (e) {
      _logger.e('Unknown Error rescheduling meeting: ${e.toString()}');
      throw Exception('An unexpected error occurred while rescheduling the meeting.');
    }
  }

  Future<QuerySnapshot<Map<String, dynamic>>> getPaginatedMeetings({
    required int limit,
    DocumentSnapshot? lastDocument,
  }) async {
    try {
      Query allMeetingsQuery = _meetingsCollection
      // Order by a field that represents age (like createdAt or startTime)
      // We order descending so the newest/active items show first, but for
      // the archive section, we will reverse the list to show newest first.
          .orderBy('startTime', descending: true)
          .limit(limit);

      if (lastDocument != null) {
        // Start after the last document fetched to get the next page
        allMeetingsQuery = allMeetingsQuery.startAfterDocument(lastDocument);
      }

      _logger.d('Fetching paginated meetings (Limit: $limit, Start After: ${lastDocument?.id ?? 'none'})');

      final querySnapshot = await allMeetingsQuery.get();

      _logger.i('Successfully fetched ${querySnapshot.docs.length} documents for the page.');
      return querySnapshot as QuerySnapshot<Map<String, dynamic>>;

    } on FirebaseException catch (e) {
      _logger.e('Firebase Error fetching paginated meetings: ${e.code} - ${e.message}');
      throw Exception('Failed to load paginated meetings: ${e.message}');
    } catch (e) {
      _logger.e('Unknown Error fetching paginated meetings: ${e.toString()}');
      throw Exception('An unexpected error occurred while loading meetings.');
    }
  }
}
